//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISEAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int id_audit { get; set; }
        public int id_campo { get; set; }
        public int id_registro { get; set; }
        public string valor_antiguo { get; set; }
        public string valor_nuevo { get; set; }
        public System.DateTime fecha_hora_audit { get; set; }
        public string usuario_modifica { get; set; }
    
        public virtual bCampo bCampo { get; set; }
    }
}
