//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISEAC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntStdUniAtd : DbContext
    {
        public EntStdUniAtd()
            : base("name=EntStdUniAtd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<bCampo> bCampo { get; set; }
        public virtual DbSet<bTabla> bTabla { get; set; }
        public virtual DbSet<ScaAfiliacion> ScaAfiliacion { get; set; }
        public virtual DbSet<SplActividad> SplActividad { get; set; }
        public virtual DbSet<SsgCuenta> SsgCuenta { get; set; }
        public virtual DbSet<SsgCuentaPermiso> SsgCuentaPermiso { get; set; }
        public virtual DbSet<SsgUsuario> SsgUsuario { get; set; }
        public virtual DbSet<StbCatalogo> StbCatalogo { get; set; }
        public virtual DbSet<StbContactoPersona> StbContactoPersona { get; set; }
        public virtual DbSet<StbParametro> StbParametro { get; set; }
        public virtual DbSet<StbPersona> StbPersona { get; set; }
        public virtual DbSet<StbValorCatalogo> StbValorCatalogo { get; set; }
        public virtual DbSet<StbValorParametro> StbValorParametro { get; set; }
        public virtual DbSet<StiNoticia> StiNoticia { get; set; }
        public virtual DbSet<StiNotificacion> StiNotificacion { get; set; }
        public virtual DbSet<StbCarrera> StbCarrera { get; set; }
        public virtual DbSet<StbFacultad> StbFacultad { get; set; }
        public virtual DbSet<StbDepartamento> StbDepartamento { get; set; }
    
        public virtual ObjectResult<spGetCatalogo_Result> spGetCatalogo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCatalogo_Result>("spGetCatalogo");
        }
    
        public virtual ObjectResult<spGetValorCatalogo_Result> spGetValorCatalogo(Nullable<int> nStbCatalogoID)
        {
            var nStbCatalogoIDParameter = nStbCatalogoID.HasValue ?
                new ObjectParameter("nStbCatalogoID", nStbCatalogoID) :
                new ObjectParameter("nStbCatalogoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetValorCatalogo_Result>("spGetValorCatalogo", nStbCatalogoIDParameter);
        }
    
        public virtual ObjectResult<spGetCargoCuenta_Result> spGetCargoCuenta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCargoCuenta_Result>("spGetCargoCuenta");
        }
    
        public virtual ObjectResult<spGetAllValorCatalogo_Result> spGetAllValorCatalogo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllValorCatalogo_Result>("spGetAllValorCatalogo");
        }
    }
}
