//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISEAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SsgCuentaPermiso
    {
        public int nSsgCuentaPermisoID { get; set; }
        public Nullable<int> nSsgCuentaID { get; set; }
        public Nullable<int> nSsgPermisoID { get; set; }
        public Nullable<byte> nActivo { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaCreacion { get; set; }
        public string sUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
    
        public virtual SsgCuenta SsgCuenta { get; set; }
        public virtual StbValorCatalogo StbValorCatalogo { get; set; }
    }
}
