//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISEAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StbContactoPersona
    {
        public int nStbContactoPersonaID { get; set; }
        public int nStbPersonaID { get; set; }
        public int nTipoContactoID { get; set; }
        public string sDescripcion { get; set; }
        public string sUsuarioCreacion { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
    
        public virtual StbPersona StbPersona { get; set; }
        public virtual StbValorCatalogo StbValorCatalogo { get; set; }
    }
}
