//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISEAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StbDepartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StbDepartamento()
        {
            this.ScaAfiliacion = new HashSet<ScaAfiliacion>();
        }
    
        public int nStbDepartamentoID { get; set; }
        public int nStbCarreraID { get; set; }
        public string sCodigoInterno { get; set; }
        public string sDescripcion { get; set; }
        public int nActivo { get; set; }
        public string sUsuarioCreacion { get; set; }
        public System.DateTime dFechaCreacion { get; set; }
        public string sUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaAfiliacion> ScaAfiliacion { get; set; }
        public virtual StbCarrera StbCarrera { get; set; }
    }
}
