//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISEAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StbValorCatalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StbValorCatalogo()
        {
            this.ScaAfiliacion = new HashSet<ScaAfiliacion>();
            this.ScaAfiliacion1 = new HashSet<ScaAfiliacion>();
            this.ScaAfiliacion2 = new HashSet<ScaAfiliacion>();
            this.ScaAfiliacion3 = new HashSet<ScaAfiliacion>();
            this.ScaAfiliacion4 = new HashSet<ScaAfiliacion>();
            this.SplActividad = new HashSet<SplActividad>();
            this.SplActividad1 = new HashSet<SplActividad>();
            this.SsgCuentaPermiso = new HashSet<SsgCuentaPermiso>();
            this.SsgUsuario = new HashSet<SsgUsuario>();
            this.StbContactoPersona = new HashSet<StbContactoPersona>();
            this.StiNotificacion = new HashSet<StiNotificacion>();
        }
    
        public int nStbValorCatalogoID { get; set; }
        public Nullable<int> nStbCatalogoID { get; set; }
        public string sCodigoInterno { get; set; }
        public string sDescripcion { get; set; }
        public Nullable<int> nActivo { get; set; }
        public string sUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> dFechaCreacion { get; set; }
        public string sUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> dFechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaAfiliacion> ScaAfiliacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaAfiliacion> ScaAfiliacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaAfiliacion> ScaAfiliacion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaAfiliacion> ScaAfiliacion3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScaAfiliacion> ScaAfiliacion4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SplActividad> SplActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SplActividad> SplActividad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SsgCuentaPermiso> SsgCuentaPermiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SsgUsuario> SsgUsuario { get; set; }
        public virtual StbCatalogo StbCatalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StbContactoPersona> StbContactoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StiNotificacion> StiNotificacion { get; set; }
    }
}
