//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISEAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StiNotificacion
    {
        public int nStiNotificacionID { get; set; }
        public Nullable<int> nStbTipoNotificacion { get; set; }
        public Nullable<int> nSgrCampoUnionID { get; set; }
        public Nullable<System.DateTime> dFechaHoraNotificacion { get; set; }
        public Nullable<int> nLeida { get; set; }
        public string sDescripcion { get; set; }
        public string sLinkReferencia { get; set; }
    
        public virtual StbValorCatalogo StbValorCatalogo { get; set; }
    }
}
